server:
  port: 8080

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由"

      routes:
        - id: service-member #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8761  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://service-member #匹配后提供服务的路由地址-------这里用的动态路由格式统一为 lb://注册进eureka服务中心的名字
          predicates:
            - Path=/member/** #断言，路径相匹配的进行路由（断言也就是匹配方式），当识别到/service-member/**时就会跳转上面的uri
#          filters: #这个必须写
#            - StripPrefix=1  #  请求/name/bar/foo，去除掉前面两个前缀之后，最后转发到目标服务的路径为/foo-----这里写的是只去掉一个，多了自然会导致路径错误，不同的访问url配置也不同

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
